# -*- coding: utf-8 -*-
"""linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184q6xGPmWW_QMMg7GprJCPfZTvxvWGbc
"""

import os

os.environ['KAGGLE_USERNAME'] = 'hariharanehari'
os.environ['KAGGLE_KEY'] = 'KGAT_772c0e4402edb3a9a9b11e613efeeba9'

!pip install kaggle

!kaggle datasets download -d andonians/random-linear-regression

!unzip random-linear-regression.zip
!ls

import pandas as pd
!kaggle datasets download -d andonians/random-linear-regression -p .
!unzip -o random-linear-regression.zip
df = pd.read_csv('train.csv')

print(len(df))
print(df.shape)
print(df.info())
print(df.head())
print(df.tail())
df.duplicated().sum()

print(df.describe)

print(df.columns)

print(df.isnull().sum())

df.duplicated().sum()

"""## Preprocessing Steps for Linear Regression Model

To prepare data for a linear regression model, the following preprocessing steps are typically performed:

1.  **Handle Missing Values:**
    *   Identify columns with missing data.
    *   Choose an appropriate strategy to fill (impute) or remove missing values. Common methods include mean, median, mode imputation, or dropping rows/columns with too many missing values.

2.  **Handle Outliers:**
    *   Identify extreme values that might disproportionately affect the model.
    *   Strategies include removing outliers, capping (winsorizing) them, or transforming the data.

3.  **Feature Scaling (Normalization/Standardization):**
    *   Linear regression models are sensitive to the scale of features. It's often beneficial to scale numerical features.
    *   **Normalization (Min-Max Scaling):** Scales features to a fixed range, usually 0 to 1.
    *   **Standardization (Z-score Normalization):** Scales features to have a mean of 0 and a standard deviation of 1.

4.  **Encode Categorical Variables:**
    *   If your dataset contains categorical features, they need to be converted into a numerical format that the model can understand.
    *   **One-Hot Encoding:** Creates new binary columns for each category.
    *   **Label Encoding:** Assigns a unique integer to each category (use with caution for nominal data).

5.  **Feature Engineering (Optional but Recommended):**
    *   Create new features from existing ones to improve model performance. This could include polynomial features, interaction terms, or aggregating data.

6.  **Split Data:**
    *   Divide the dataset into training and testing sets to evaluate the model's performance on unseen data. A common split is 70-80% for training and 20-30% for testing.

## Split Data into Training and Testing Sets

It's important to split the dataset into training and testing sets. The training set is used to train the model, while the testing set is used to evaluate its performance on unseen data, preventing overfitting. A common split ratio is 80% for training and 20% for testing.
"""

from sklearn.model_selection import train_test_split


X = df[['x']]
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""## Handle Missing Values

As observed earlier, the `y` column has one missing value. Since `y` is our target variable, and there's only a single missing entry, the most straightforward approach is to remove the row containing this missing value. This ensures that our model isn't trained or evaluated on incomplete target data.
"""

missing_in_y_train = y_train.isnull().sum()
missing_in_y_test = y_test.isnull().sum()

print(f"Missing values in y_train: {missing_in_y_train}")
print(f"Missing values in y_test: {missing_in_y_test}")

if missing_in_y_train > 0:
    print(f"Dropping {missing_in_y_train} row(s) from X_train and y_train due to missing 'y' values.")
    valid_indices_train = y_train.dropna().index
    X_train = X_train.loc[valid_indices_train]
    y_train = y_train.loc[valid_indices_train]

if missing_in_y_test > 0:
    print(f"Dropping {missing_in_y_test} row(s) from X_test and y_test due to missing 'y' values.")
    valid_indices_test = y_test.dropna().index
    X_test = X_test.loc[valid_indices_test]
    y_test = y_test.loc[valid_indices_test]

print(f"\nAfter handling missing values:")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""## Feature Scaling: Standardization

For linear regression, it's often beneficial to scale numerical features. Standardization (Z-score normalization) transforms the data to have a mean of 0 and a standard deviation of 1. This helps in making the optimization process more stable and can prevent features with larger magnitudes from dominating the learning process.
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled (first 5 rows):\n", X_train_scaled[:5])
print("\nX_test_scaled (first 5 rows):\n", X_test_scaled[:5])


import numpy as np
print(f"\nMean of X_train_scaled: {np.mean(X_train_scaled):.2f}")
print(f"Standard deviation of X_train_scaled: {np.std(X_train_scaled):.2f}")

"""## Train the Linear Regression Model

Now that the data has been preprocessed (missing values handled, and features scaled), we can train a Linear Regression model. We will use the `LinearRegression` model from `sklearn.linear_model`.
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

model = LinearRegression()


model.fit(X_train_scaled, y_train)

print("Model training complete.")
print(f"Coefficients: {model.coef_}")
print(f"Intercept: {model.intercept_}")
print(f"R^2 score: {model.score(X_test_scaled, y_test)}")

y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {np.sqrt(mse)}")
print(f"Mean Absolute Error: {mae}")

