# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCrZrz3qKUBxbC6HSe1EF4wLCil2lPhL
"""

import os

os.environ['KAGGLE_USERNAME'] = 'hariharanehari'
os.environ['KAGGLE_KEY'] = 'KGAT_772c0e4402edb3a9a9b11e613efeeba9'

!pip install kaggle

!kaggle datasets download -d yasserh/titanic-dataset

!unzip titanic-dataset.zip
!ls

import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

df.head(10)

print(len(df))
print(df.shape)
print(df.info)
print(df.head)
print(df.tail)
df.duplicated().sum()

print(df.describe)

print(df.columns)

print(df.isnull().sum())

df.duplicated().sum()