# -*- coding: utf-8 -*-
"""traingprograms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZtZ_alKW-q6c4okQOpkF_hb0kH06dHT
"""

#palindrome
n=input()
a=n[::-1]
print(a)
if a==n:
  print("string is a palindrome")
else:
    print("string is not a palindrome")

a = 15
b = 15.0
print(a==b)

#slicing
n=input()
m=n[4::-1]
print(m)

#factorial
n=int(input())
fact = 1
for i in range(1,n+1):
  fact = fact*i
print(fact)



#amstrong  no
a = int(input())
length = len(str(a))
s = 0
temp = a
while temp>0:
  d = temp % 10
  s += d**length
  temp = temp//10
  if(s==a):
    print("amstrong")
  else:
      print("not an amstrong")

#prime no - 1-50

for num in range(1, 51):
    if num > 1:
        is_prime = True

        for i in range(2, num):
            if num % i == 0:
                is_prime = False
                break

        if is_prime:
            print(num)



#cel to fah
celsius = float(input("Enter temperature in Celsius: "))

fahrenheit = (celsius * 9/5) + 32

print("Temperature in Fahrenheit:", fahrenheit)

#fah to cel
fahrenheit = float(input("Enter temperature in far: "))

celcius = (fahrenheit * 9/5) - 32

print("Temperature in Fahrenheit:", fahrenheit)

a = "1 2"
b = a.split(",")
print(a)

#fibonacci
a=0
b=1
n=5
print(a)
print(b)
for i in range(n):
  c=a+b
  a=b
  b=c
  print(c)

#swapping without third variable
a=int(input())
b=int(input())
print("Before swapping")
print("A=",a);print("B=",b)
print("After swapping")
a,b=b,a
print("A=",a);print("B=",b)

#vowels

text = input("Enter a string: ")

vowels = "aeiouAEIOU"
count = 0

print("Vowels in the string are:")

for ch in text:
    if ch in vowels:
        print(ch, end=" ")
        count += 1

print("\nTotal number of vowels:", count)

#word count
text = input("Enter a string: ")


count = 0

print("Vowels in the string are:")

for ch in text:

        print(ch, end=" ")
        count += 1

print("\nTotal number of vowels:", count)

# Find the smallest and largest number
n =[3,17,2,9,7,65,92]
print(min(n))
print(max(n))

n = int(input())
m = int(input())
print("add:",n+m)
print("sub:",n-m)
print("mul:",n*m)
print("div:",n/m)

a=int(input("enter the first no: "))
b=int(input("enter the second no: "))
x=a
y=b
while y!=0:
    x,y=y,x%y
gcd = x
lcm = (a*b)//gcd
print("gcd is :",gcd)
print("lcm is :",lcm)

# positive or negative
n = int(input())
if n>0:
  print("positive")
if n==0:
  print("zero")
if n<0:
  print("negative")

#leap year
n=int(input())
if (n % 400  == 0):
  print("leap year")
elif (n%4 ==0 and n%100!= 0):
  print("leap year")
else:
  print("not a leap year")

# even or odd
n=int(input())
if n%2 == 0:
  print("even")
else:
  print("odd")

#annagram
a=input()
b=input()
if sorted(a)==sorted(b):
  print("annagram")
else:
  print("not an annagram")

for i in range(1,6):
  for j in range(1,i+1):
    print(j, end=" ")
  print()

for i in range(6,0,-1):
  for j in range(1,i+1):
    print("*", end=" ")
  print()

for i in range(1,4):
  for j in range(1,i+1):
    print("*", end= "")
  print()

n=6
for i in range(n):
  print( "_"* i+"*"*(n-i))

row=8
for i in range(1 , row+1):
  print("*"*(i-1))

rows = 5

for i in range(1, rows + 1):
    print(" " * (rows - i), end="")
    print("*" * (2 * i - 1))

t = int(input())
for i in range(t):
    n=int(input())
    fact=t
    for i in range(1,n+1):
        fact=fact*i

    print(fact)

str1 = input()
str2 = input()
if str1[1] != str2[1]:
  print("yes")
elif str1[0] != str2[0]:
  print("yes")
elif str1[2] != str2[2]:
  print("yes")
else:
  print("no")

n = input()
rev = n[3:13:1]
print(rev)

input_string = input()
count  = 0
ch = input_string[0]

for char_in_string in input_string:
  if char_in_string == ch:
    count += 1
print(count)

n = int(input())
x = list(map(int,input().split()))
for i in range(len(x)):
  d = x[i]
  if d == 0:
    if i > 0:
      d = x[i-1]+1
    else:
      d = 1
  print(d)

from os import name
# class and objects
class student:

  def __init__(self,name,age):
    self.name = name
    self.age = age
  def display(self):
    print("name:",self.name)
    print("age:",self.age)

# Create an object and call its method outside the class definition
obj = student("hems",3)
obj.display()

# inheritance
class father:
  def bike(self):
    print("father has a bike")
class son(father):
  def cycle(self):
    print("son has cycle")

obj = son()
obj.cycle()
obj.bike()

# abstraction
class bank:
  def __init__(self):
    self.__balance = 0
  def deposit(self,amount)

from abc import ABC, abstractmethod

class Animal(ABC):

    @abstractmethod
    def sound(self):
        pass

class Dog(Animal):

    def sound(self):
        print("Bark")

d = Dog()
d.sound()

import builtins

n = int(builtins.input())

r = int(builtins.str(n)[::-1])

def p(x):
    if x < 2:
        return False
    for i in builtins.range(2, x):
        if x % i == 0:
            return False
    return True

builtins.print("Prime" if p(n) and p(r) else "Not Prime")

n = int(input())

a = int(str(n * n)[::-1])
b = int(str(n)[::-1]) ** 2

if a == b:
    print("Adam Number")
else:
    print("Not Adam Number")

import os

os.environ['KAGGLE_USERNAME'] = 'hariharanehari'
os.environ['KAGGLE_KEY'] = 'KGAT_772c0e4402edb3a9a9b11e613efeeba9'

!pip install kaggle

!kaggle datasets download -d yasserh/titanic-dataset

!unzip titanic-dataset.zip
!ls

import pandas as pd

df = pd.read_csv("The Titanic dataset.csv")


df.head(10)

print(len(df))
print(df.shape)
print(df.info)
print(df.head)
print(df.tail)
df.duplicated().sum()

print(df.describe)

print(df.columns)

print(df.isnull().sum())

import numpy as np
import pandas as pd

new_columns = [str(x) for x in df.iloc[0].values]


if new_columns[3] == 'nan':
    new_columns[3] = 'name'

# Rename the column at index 5 to 'age'
new_columns[5] = 'age'

df.columns = new_columns


df = df.drop(df.index[0])


df['age'] = df['age'].replace('?', np.nan)
df['age'] = pd.to_numeric(df['age'], errors='coerce')


df['age'] = df['age'].fillna(df['age'].median())

print(df[['age']].head(10))
print(df['age'].isnull().sum())

print(df['age'].isnull().sum())

import numpy as np
import pandas as pd

# Re-apply column renaming and initial row drop, as df appears to be in an unprocessed state.
# new_columns is already available in the kernel state with the correct names.

df.columns = new_columns
df = df.drop(df.index[0])

# Re-apply age column processing
df['age'] = df['age'].replace('?', np.nan)
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = df['age'].fillna(df['age'].median())


print(df[['age']].head(10))
print(df.isnull().sum())